---
plugin: aws_ec2
regions:
  - us-east-1
filters:
  tag:environment: dev
  tag:service: rewards
  instance-state-name: running
keyed_groups:
  - key: tags.environment
    prefix: env
  - key: tags.service
    prefix: service
  - key: tags.AnsibleManaged
    prefix: tag_AnsibleManaged
hostnames:
  - instance-id
compose:
  ansible_host: instance_id
