---
- name: Configure Rewards Web Tier
  hosts: tag_Environment_dev:&tag_Service_rewards:&tag_AnsibleManaged_true
  become: yes
  gather_facts: yes
  
  vars:
    git_commit: "{{ lookup('env', 'GITHUB_SHA') | default('local-dev', true) }}"
    aws_region: "{{ lookup('env', 'AWS_REGION') | default('us-east-1', true) }}"
  
  roles:
    - role: common
      tags: ['common', 'baseline']
    
    - role: health-service
      tags: ['health-service', 'app']
    
    - role: observability
      tags: ['observability', 'monitoring']
